apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  namespace: dev
  annotations:
    # ArgoCD hook: ejecutar después de que todos los recursos estén desplegados
    argocd.argoproj.io/hook: PostSync
    # borrar el hook si tuvo éxito
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migrate
          image: docker.io/tomasignacio/backend:abad65b19d1563720acb59fbd7c2b4ecd9670951
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: dev-secrets
            - configMapRef:
                name: dev-config
          command: [ "sh", "-c", "python manage.py migrate --noinput && python manage.py showmigrations" ]
      restartPolicy: OnFailure
