apiVersion: v1
kind: Secret
metadata:
  name: dev-secrets
  namespace: dev
type: Opaque
stringData:
  SECRET_KEY: "762dc3552dde90a4b860e39cf86a0643f9ab6155484e26920eb4ef13a8de896f"
  SQL_PASSWORD: "secret"
  SQL_USER: "devuser"